# Generated by Django 5.2.8 on 2025-11-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('original_url', models.TextField()),
                ('download_path', models.TextField()),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('format_info', models.JSONField(default=dict)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('download_count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'download_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
